import GithubSlugger from 'github-slugger'
import type { TocEntry } from './remarkToc'

export interface EditorTocEntry extends TocEntry {
  /** 1-based line number in the source text. */
  line: number
}

/**
 * Extract headings from raw markdown source using regex.
 * Much cheaper than running the full unified pipeline —
 * suitable for real-time updates during editing.
 *
 * Uses `github-slugger` to match IDs generated by `rehype-slug`.
 */
export function extractHeadingsFromSource(source: string): EditorTocEntry[] {
  const entries: EditorTocEntry[] = []
  const lines = source.split('\n')
  const slugger = new GithubSlugger()

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(/^(#{1,6})\s+(.+)$/)
    if (match) {
      const depth = match[1].length
      const text = match[2].trim()
      entries.push({
        depth,
        text,
        id: slugger.slug(text),
        line: i + 1,
      })
    }
  }

  return entries
}
